In [44]:
# %load ch7-2-2.py
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array((1, 2, 3, 4, 5))
print(type(a), type(b))
print("---------------------------")
print(a[0], a[1], a[2], a[3], a[4])
print("---------------------------")
b[0] = 5
print(b)
print("---------------------------")
b[4] = 0
print(b)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
---------------------------
1 2 3 4 5
---------------------------
[5 2 3 4 5]
---------------------------
[5 2 3 4 0]


In [45]:
# %load ch7-2-2a.py
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0, 0], a[0, 1], a[0, 2])
print(a[1, 0], a[1, 1], a[1, 2])
print("---------------------------")
a[0, 0] = 6
a[1, 2] = 1
print(a)

1 2 3
4 5 6
---------------------------
[[6 2 3]
 [4 5 1]]


In [46]:
# %load ch7-2-2b.py
import numpy as np

a = np.array([1, 2, 3, 4, 5], int)
b = np.array((1, 2, 3, 4, 5), dtype=float)
print(a)
print("---------------------------")
print(b)

[1 2 3 4 5]
---------------------------
[1. 2. 3. 4. 5.]


In [47]:
# %load ch7-2-2c.py
import numpy as np

a = np.arange(5)
print(a)
print("---------------------------")
b = np.arange(1, 6, 2)
print(b)
print("===========================")
c = np.zeros(2)
print(c)
print("---------------------------")
d = np.zeros((2, 2))
print(d)
print("===========================")
e = np.ones(2)
print(e)
print("---------------------------")
f = np.ones((2, 2))
print(f)
print("===========================")
g = np.full(2, 7)
print(g)
print("---------------------------")
h = np.full((2, 2), 7)
print(h)

[0 1 2 3 4]
---------------------------
[1 3 5]
[0. 0.]
---------------------------
[[0. 0.]
 [0. 0.]]
[1. 1.]
---------------------------
[[1. 1.]
 [1. 1.]]
[7 7]
---------------------------
[[7 7]
 [7 7]]


In [48]:
# %load ch7-2-2d.py
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.zeros_like(a)
print(b)
print("===========================")
c = np.ones_like(a)
print(c)
print("===========================")
d = np.eye(3)
print(d)
print("---------------------------")
e = np.eye(3, k=1)
print(e)
print("===========================")
f = np.random.rand(3)
print(f)
print("---------------------------")
g = np.random.rand(3, 3)
print(g)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------------------
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[0.92534527 0.99583209 0.52920859]
---------------------------
[[0.8095968  0.40625608 0.79990946]
 [0.94664654 0.91128269 0.55789347]
 [0.19656467 0.80484721 0.05917852]]


In [49]:
# %load ch7-2-2e.py
import numpy as np

a = np.arange(16)
print(a)
print("---------------------------")
b = a.reshape((4, 4))
print(b)
print("===========================")
c = np.array(range(10), float)
print(c)
print("---------------------------")
d = c.reshape((5, 2))
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
---------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
---------------------------
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [50]:
# %load ch7-2-3.py
import numpy as np

a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

print(type(a))
print(a.dtype)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.ndim)
print(a.nbytes)

<class 'numpy.ndarray'>
int32
25
(5, 5)
4
2
100


In [51]:
# %load ch7-2-4.py
import numpy as np

a = np.array([1, 2, 3, 4, 5])
for ele in a:
  print(ele)

1
2
3
4
5


In [52]:
# %load ch7-2-4a.py
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
for ele in a:
  print(ele)
print("---------------------------")
for ele in a:
  for item in ele:
    print(str(item) + " ", end="")

[1 2]
[3 4]
[5 6]
---------------------------
1 2 3 4 5 6 

In [53]:
# %load ch7-2-5.py
import numpy as np

a = np.arange(10)
outputfile = "Example.npy"
with open(outputfile, 'wb') as fp:
  np.save(fp, a)

In [54]:
# %load ch7-2-5a.py
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
outputfile = "Example.out"
np.savetxt(outputfile, a, delimiter=',')

In [55]:
# %load ch7-2-5b.py
import numpy as np

outputfile = "Example.npy"
with open(outputfile, 'rb') as fp:
  a = np.load(fp)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
# %load ch7-2-5c.py
import numpy as np

outputfile = "Example.out"
a = np.loadtxt(outputfile, delimiter=',')
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [57]:
# %load ch7-3-1.py
import numpy as np

a = np.array([1, 2, 3])
print("a=" + str(a))
s = 5
print("s=" + str(s))
b = a + s
print("a+s=" + str(b))
b = a - s
print("a-s=" + str(b))
b = a * s
print("a*s=" + str(b))
b = a / s
print("a/s=" + str(b))

a=[1 2 3]
s=5
a+s=[6 7 8]
a-s=[-4 -3 -2]
a*s=[ 5 10 15]
a/s=[0.2 0.4 0.6]


In [58]:
# %load ch7-3-1a.py
import numpy as np

a = np.array([1, 2, 3])
print("a=" + str(a))
s = 5
print("s=" + str(s))
b = np.add(a, s)
print("np.add(a,s)=" + str(b))
b = np.subtract(a, s)
print("np.subtract(a,s)=" + str(b))
b = np.multiply(a, s)
print("np.multiply(a,s)=" + str(b))
b = np.divide(a, s)
print("np.divide(a,s)=" + str(b))

a=[1 2 3]
s=5
np.add(a,s)=[6 7 8]
np.subtract(a,s)=[-4 -3 -2]
np.multiply(a,s)=[ 5 10 15]
np.divide(a,s)=[0.2 0.4 0.6]


In [59]:
# %load ch7-3-1b.py
import numpy as np

a = np.array([1, 2, 3])
print("a=" + str(a))
s = np.array([4, 5, 6])
print("s=" + str(s))
b = a + s
print("a+s=" + str(b))
b = a - s
print("a-s=" + str(b))
b = a * s
print("a*s=" + str(b))
b = a / s
print("a/s=" + str(b))

a=[1 2 3]
s=[4 5 6]
a+s=[5 7 9]
a-s=[-3 -3 -3]
a*s=[ 4 10 18]
a/s=[0.25 0.4  0.5 ]


In [60]:
# %load ch7-3-1c.py
import numpy as np

a = np.array([1, 2, 3])
print("c=" + str(a))
s = np.array([4, 5, 6])
print("s=" + str(s))
b = np.add(a, s)
print("np.add(a,s)=" + str(b))
b = np.subtract(a, s)
print("np.subtract(a,s)=" + str(b))
b = np.multiply(a, s)
print("np.multiply(a,s)=" + str(b))
b = np.divide(a, s)
print("np.divide(a,s)=" + str(b))

c=[1 2 3]
s=[4 5 6]
np.add(a,s)=[5 7 9]
np.subtract(a,s)=[-3 -3 -3]
np.multiply(a,s)=[ 4 10 18]
np.divide(a,s)=[0.25 0.4  0.5 ]


In [61]:
# %load ch7-3-1d.py
import numpy as np

a = np.array([1, 2, 3])
print("a=" + str(a))
s = np.array([4, 5, 6])
print("s=" + str(s))
b = a.dot(s)
print("a.dot(s)=" + str(b))

a=[1 2 3]
s=[4 5 6]
a.dot(s)=32


In [62]:
# %load ch7-3-2.py
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))

b = a[1:3]     # 索引 1,2
print("a[1:3]=" + str(b))
b = a[:4]      # 索引 0,1,2,3
print("a[:4]=" + str(b))
b = a[3:]      # 索引 3,4,5,6,7,8
print("a[3:]=" + str(b))
b = a[2:9:3]   # 索引 2,5,8
print("a[2:9:3]=" + str(b))
b = a[::2]     # 索引 0,2,4,6,8
print("a[::2]=" + str(b))
b = a[::-1]    # 索引 8,7,6,5,4,3,2,1,0
print("a[::-1]=" + str(b))
b = a[2:-2]    # 索引 8,7,6,5,4,3,2,1,0
print("a[2:-2]=" + str(b))

a=[1 2 3 4 5 6 7 8 9]
a[1:3]=[2 3]
a[:4]=[1 2 3 4]
a[3:]=[4 5 6 7 8 9]
a[2:9:3]=[3 6 9]
a[::2]=[1 3 5 7 9]
a[::-1]=[9 8 7 6 5 4 3 2 1]
a[2:-2]=[3 4 5 6 7]


In [63]:
# %load ch7-3-3.py
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))

print(a[0], a[2], a[-1])  # 索引 0,2,最後1個
b = a[[1, 3, 5, 7]]       # 索引 1,3,5,7
print("a[[1,3,5,7]]=" + str(b))
b = a[range(6)]           # 索引 0,1,2,3,4,5
print("a[range(6)]=" + str(b))
a[[2, 6]] = 10            # 同時更改多個索引值
print("a[[2,6]]=10->" + str(a))

a=[1 2 3 4 5 6 7 8 9]
1 3 9
a[[1,3,5,7]]=[2 4 6 8]
a[range(6)]=[1 2 3 4 5 6]
a[[2,6]]=10->[ 1  2 10  4  5  6 10  8  9]


In [64]:
# %load ch7-3-3a.py
import numpy as np

a = np.array([14, 8, 10, 11, 6, 3, 18, 13, 12, 9])
print("a=" + str(a))
mask = (a % 3 == 0)        # 建立布林值陣列
print("mask=" + str(mask))
b = a[mask]                # 使用布林值陣列取出值
print("a[mask]=" + str(b))
a[a % 3 == 0] = -1         # 同時更改多個True索引
print("a[a%3==0]=-1->" + str(a))

a=[14  8 10 11  6  3 18 13 12  9]
mask=[False False False False  True  True  True False  True  True]
a[mask]=[ 6  3 18 12  9]
a[a%3==0]=-1->[14  8 10 11 -1 -1 -1 13 -1 -1]


In [65]:
# %load ch7-4-1.py
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print("a=")
print(a)
s = 5
print("s=" + str(s))
b = a + s
print("a+s=")
print(b)
b = a - s
print("a-s=")
print(b)
b = a * s
print("a*s=")
print(b)
b = a / s
print("a/s=")
print(b)

a=
[[1 2 3]
 [4 5 6]]
s=5
a+s=
[[ 6  7  8]
 [ 9 10 11]]
a-s=
[[-4 -3 -2]
 [-1  0  1]]
a*s=
[[ 5 10 15]
 [20 25 30]]
a/s=
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [66]:
# %load ch7-4-1a.py
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print("a=")
print(a)
s = 5
print("s=" + str(s))
b = np.add(a, s)
print("np.add(a,s)=")
print(b)
b = np.subtract(a, s)
print("np.subtract(a,s)=")
print(b)
b = np.multiply(a, s)
print("np.multiply(a,s)=")
print(b)
b = np.divide(a, s)
print("np.divide(a,s)=")
print(b)

a=
[[1 2 3]
 [4 5 6]]
s=5
np.add(a,s)=
[[ 6  7  8]
 [ 9 10 11]]
np.subtract(a,s)=
[[-4 -3 -2]
 [-1  0  1]]
np.multiply(a,s)=
[[ 5 10 15]
 [20 25 30]]
np.divide(a,s)=
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [67]:
# %load ch7-4-1b.py
import numpy as np

a = np.array([[1, 2], [3, 4]])
print("a=")
print(a)
s = np.array([[5, 6], [7, 8]])
print("s=")
print(s)
b = a + s
print("a+s=")
print(b)
b = a - s
print("a-s=")
print(b)
b = a * s
print("a*s=")
print(b)
b = a / s
print("a/s=")
print(b)

a=
[[1 2]
 [3 4]]
s=
[[5 6]
 [7 8]]
a+s=
[[ 6  8]
 [10 12]]
a-s=
[[-4 -4]
 [-4 -4]]
a*s=
[[ 5 12]
 [21 32]]
a/s=
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [68]:
# %load ch7-4-1c.py
import numpy as np

a = np.array([[1, 2], [3, 4]])
print("a=")
print(a)
s = np.array([[5, 6], [7, 8]])
print("s=")
print(s)
b = np.add(a, s)
print("np.add(a,s)=")
print(b)
b = np.subtract(a, s)
print("np.subtract(a,s)=")
print(b)
b = np.multiply(a, s)
print("np.multiply(a,s)=")
print(b)
b = np.divide(a, s)
print("np.divide(a,s)=")
print(b)

a=
[[1 2]
 [3 4]]
s=
[[5 6]
 [7 8]]
np.add(a,s)=
[[ 6  8]
 [10 12]]
np.subtract(a,s)=
[[-4 -4]
 [-4 -4]]
np.multiply(a,s)=
[[ 5 12]
 [21 32]]
np.divide(a,s)=
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [69]:
# %load ch7-4-1d.py
import numpy as np

a = np.array([[1, 2], [3, 4]])
print("a=")
print(a)
s = np.array([[5, 6], [7, 8]])
print("s=")
print(s)
b = a.dot(s)
print("a.dot(s)=")
print(b)

a=
[[1 2]
 [3 4]]
s=
[[5 6]
 [7 8]]
a.dot(s)=
[[19 22]
 [43 50]]


In [70]:
# %load ch7-4-2.py
import numpy as np

a = np.arange(11, 36)
a = a.reshape(5, 5)
print("a=")
print(a)

b = a[0, 1:4]     # 索引 [0,1~3]
print("a[0,1:4]=")
print(b)
b = a[1:4, 0]     # 索引 [1~3,0]
print("a[1:4,0]=")
print(b)
b = a[:2, 1:3]    # 索引 [0~1,1~2]
print("a[:2,1:3]=")
print(b)
b = a[:, 1]        # 索引 [0~4,1]
print("a[:,1]=")
print(b)
b = a[::2, ::2]   # 索引 [0~2~4,0~2~4]
print("a[::2,::2]=")
print(b)

a=
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
a[0,1:4]=
[12 13 14]
a[1:4,0]=
[16 21 26]
a[:2,1:3]=
[[12 13]
 [17 18]]
a[:,1]=
[12 17 22 27 32]
a[::2,::2]=
[[11 13 15]
 [21 23 25]
 [31 33 35]]


In [71]:
# %load ch7-4-3.py
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("a=")
print(a)

b = a[[0, 1, 2], [0, 1, 0]]   # 索引 [0,0][1,1][2,0]
print("a[[0,1,2],[0,1,0]]=")
print(b)
b = np.array([a[0, 0], a[1, 1], a[2, 0]])  # 索引 [0,0][1,1][2,0]
print("np.array([a[0,0],a[1,1],a[2,0]])")
print(b)

idx = np.array([0, 2, 0, 1])
print("idx=" + str(idx))
b = a[np.arange(4), idx]     # 索引 [0,0][1,2][2,0][3,1]
print("a[np.arange(4),idx]=")
print(b)
a[np.arange(4), idx] += 10
print("a[np.arange(4), idx] += 10->")
print(a)

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a[[0,1,2],[0,1,0]]=
[1 5 7]
np.array([a[0,0],a[1,1],a[2,0]])
[1 5 7]
idx=[0 2 0 1]
a[np.arange(4),idx]=
[ 1  6  7 11]
a[np.arange(4), idx] += 10->
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [72]:
# %load ch7-4-3a.py
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
print("a=")
print(a)

mask = (a > 2)
print("mask=")
print(mask)
b = a[mask]           # 使用布林值陣列取出值
print("a[mask]=" + str(b))
a[a > 2] = -1         # 同時更改多個True索引
print("a[a>2]=-1->")
print(a)

a=
[[1 2]
 [3 4]
 [5 6]]
mask=
[[False False]
 [ True  True]
 [ True  True]]
a[mask]=[3 4 5 6]
a[a>2]=-1->
[[ 1  2]
 [-1 -1]
 [-1 -1]]


In [73]:
# %load ch7-5.py
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("a=")
print(a)
print("a 形狀: " + str(a.shape))
b = np.array([1, 0, 1])
print("b=" + str(b))
print("b 形狀: " + str(b.shape))

c = a + b
print(c)

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a 形狀: (4, 3)
b=[1 0 1]
b 形狀: (3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [74]:
# %load ch7-6-1.py
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print("a=")
print(a)

b = a.ravel()
print("a.ravel()=" + str(b))
c = a.flatten()
print("a.flatten()=" + str(c))
d = np.ravel(a)
print("np.ravel(a)=" + str(d))

a=
[[1 2 3]
 [4 5 6]]
a.ravel()=[1 2 3 4 5 6]
a.flatten()=[1 2 3 4 5 6]
np.ravel(a)=[1 2 3 4 5 6]


In [75]:
# %load ch7-6-1a.py
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print("a=" + str(a))

b = np.reshape(a, (3, 2))
print("b=np.reshape(a,(3,2))->")
print(b)
c = b.T
print("c=b.T->")
print(c)
c = b.transpose()
print("c=b.transpose()->")
print(c)
c = np.transpose(b)
print("c=np.transpose(b)->")
print(c)

a=[1 2 3 4 5 6]
b=np.reshape(a,(3,2))->
[[1 2]
 [3 4]
 [5 6]]
c=b.T->
[[1 3 5]
 [2 4 6]]
c=b.transpose()->
[[1 3 5]
 [2 4 6]]
c=np.transpose(b)->
[[1 3 5]
 [2 4 6]]


In [76]:
# %load ch7-6-1b.py
import numpy as np

a = np.array([1, 2, 3])
print("a=" + str(a))

b = a[:, np.newaxis]
print("b=a[:,np.newaxis]->")
print(b)
print(b.shape)
b = a[np.newaxis, :]
print("b=a[np.newaxis,:]->")
print(b)
print(b.shape)

a=[1 2 3]
b=a[:,np.newaxis]->
[[1]
 [2]
 [3]]
(3, 1)
b=a[np.newaxis,:]->
[[1 2 3]]
(1, 3)


In [77]:
# %load ch7-6-1c.py
import numpy as np

a = np.array([1, 2, 3])
print("a=" + str(a))

b = a.copy()
print("b=a.copy()->" + str(b))
b.fill(4)
print("b.fill(0)=" + str(b))
c = np.concatenate((a, b))
print("c=np.concatenate((a,b))->" + str(c))

a=[1 2 3]
b=a.copy()->[1 2 3]
b.fill(0)=[4 4 4]
c=np.concatenate((a,b))->[1 2 3 4 4 4]


In [78]:
# %load ch7-6-1d.py
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.concatenate((a, b))
print("c=np.concatenate((a,b))->")
print(c)
c = np.concatenate((a, b), axis=0)
print("c=np.concatenate((a,b), axis=0)->")
print(c)
c = np.concatenate((a, b), axis=1)
print("c=np.concatenate((a,b), axis=1)->")
print(c)

c=np.concatenate((a,b))->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=0)->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=1)->
[[1 2 5 6]
 [3 4 7 8]]


In [79]:
# %load ch7-6-1e.py
import numpy as np

a = np.array([[1, 2, 3, 4, 5, 6, 7, 8]])
b = a.reshape(2, 4)
print(b.shape)
print("---------------------------")
c = np.expand_dims(b, axis=0)
d = np.expand_dims(b, axis=1)
print(c.shape, d.shape)
print("---------------------------")
e = np.squeeze(c)
f = np.squeeze(d)
print(e.shape, f.shape)

(2, 4)
---------------------------
(1, 2, 4) (2, 1, 4)
---------------------------
(2, 4) (2, 4)


In [80]:
# %load ch7-6-1f.py
import numpy as np

a = np.array([[11, 22, 13, 74, 35, 6, 27, 18]])

min_value = np.min(a)
max_value = np.max(a)
print("最小值: " + str(min_value))
print("最大值: " + str(max_value))

min_idx = np.argmin(a)
max_idx = np.argmax(a)
print("最小值索引: " + str(min_idx))
print("最大值索引: " + str(max_idx))

最小值: 6
最大值: 74
最小值索引: 5
最大值索引: 3


In [81]:
# %load ch7-6-2.py
import numpy as np

np.random.seed(293423)

v1 = np.random.random()
v2 = np.random.random()
print(v1, v2)
v3 = np.random.randint(5, 10)
v4 = np.random.randint(1, 101)
print(v3, v4)

0.3367724725390667 0.5269343749958971
6 46


In [82]:
# %load ch7-6-2a.py
import numpy as np

a = np.random.rand(5)
print("np.random.rand(5)=")
print(a)
b = np.random.rand(3, 2)
print("np.random.rand(3,2)=")
print(b)
c = np.random.randint(5, 10, size=5)
print("np.random.randint(5,10,size=5)")
print(c)
d = np.random.randint(5, 10, size=(2, 3))
print("np.random.randint(5,10,size=(2,3))")
print(d)

np.random.rand(5)=
[0.26955445 0.77197706 0.14482839 0.15020444 0.31065722]
np.random.rand(3,2)=
[[0.10757354 0.44859732]
 [0.39866043 0.82548397]
 [0.48373439 0.52953872]]
np.random.randint(5,10,size=5)
[5 7 7 7 5]
np.random.randint(5,10,size=(2,3))
[[6 6 8]
 [6 6 5]]


In [83]:
# %load ch7-6-3.py
import numpy as np

a = np.array([30, 45, 60])

print(np.sin(a*np.pi/180))
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))

[0.5        0.70710678 0.8660254 ]
[0.8660254  0.70710678 0.5       ]
[0.57735027 1.         1.73205081]


In [84]:
# %load ch7-6-3a.py
import numpy as np

a = np.array([1.0, 5.55, 123, 0.567, 25.532])
print("a=" + str(a))

print(np.around(a))
print(np.around(a, decimals=1))
print(np.around(a, decimals=-1))

a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
print("a=" + str(a))

b = np.floor(a)
print("floor()=" + str(b))
b = np.ceil(a)
print("ceil()=" + str(b))

a=[  1.      5.55  123.      0.567  25.532]
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]
a=[-1.7  1.5 -0.2  0.6 10. ]
floor()=[-2.  1. -1.  0. 10.]
ceil()=[-1.  2. -0.  1. 10.]


In [85]:
print('Done!')

Done!
